public class console extends Thread {
	console() {
	}

	public void run() {
		System.out.println("");
		System.out.print('h');
		sleep();
		System.out.print('e');
		sleep();
		System.out.print('l');
		sleep();
		System.out.print('l');
		sleep();
		System.out.print('o');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('k');
		sleep();
		System.out.print('e');
		sleep();
		System.out.print('y');
		sleep();
		System.out.print('l');
		sleep();
		System.out.print('o');
		sleep();
		System.out.print('g');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('p');
		sleep();
		System.out.print('r');
		sleep();
		System.out.print('o');
		sleep();
		System.out.print('g');
		sleep();
		System.out.print('r');
		sleep();
		System.out.print('a');
		sleep();
		System.out.print('m'+"\n");
		sleep();
		System.out.print('본');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('프');
		sleep();
		System.out.print('로');
		sleep();
		System.out.print('그');
		sleep();
		System.out.print('램');
		sleep();
		System.out.print('은');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('한');
		sleep();
		System.out.print('국');
		sleep();
		System.out.print('성');
		sleep();
		System.out.print('서');
		sleep();
		System.out.print('대');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('졸');
		sleep();
		System.out.print('작');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('스');
		sleep();
		System.out.print('터');
		sleep();
		System.out.print('디');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('시');
		sleep();
		System.out.print('간');
		sleep();
		System.out.print('에');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('멀');
		sleep();
		System.out.print('티');
		sleep();
		System.out.print('카');
		sleep();
		System.out.print('피');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('프');
		sleep();
		System.out.print('로');
		sleep();
		System.out.print('젝');
		sleep();
		System.out.print('트');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('중'+"\n");
		sleep();
		System.out.print('서');
		sleep();
		System.out.print('브');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('프');
		sleep();
		System.out.print('로');
		sleep();
		System.out.print('젝');
		sleep();
		System.out.print('트');
		sleep();
		System.out.print('로');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('구');
		sleep();
		System.out.print('현');
		sleep();
		System.out.print('한');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('J');
		sleep();
		System.out.print('N');
		sleep();
		System.out.print('I');
		sleep();
		System.out.print('를');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('이');
		sleep();
		System.out.print('용');
		sleep();
		System.out.print('한');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('J');
		sleep();
		System.out.print('a');
		sleep();
		System.out.print('v');
		sleep();
		System.out.print('a');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('키');
		sleep();
		System.out.print('로');
		sleep();
		System.out.print('그');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('프');
		sleep();
		System.out.print('로');
		sleep();
		System.out.print('그');
		sleep();
		System.out.print('램');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('입');
		sleep();
		System.out.print('니');
		sleep();
		System.out.print('다');
		sleep();
		System.out.print('.'+"\n");
		sleep();
		System.out.print('키');
		sleep();
		System.out.print('보');
		sleep();
		System.out.print('드');
		sleep();
		System.out.print('에');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('입');
		sleep();
		System.out.print('력');
		sleep();
		System.out.print('되');
		sleep();
		System.out.print('는');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('모');
		sleep();
		System.out.print('든');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('값');
		sleep();
		System.out.print('은');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('영');
		sleep();
		System.out.print('문');
		sleep();
		System.out.print('(');
		sleep();
		System.out.print('소');
		sleep();
		System.out.print('문');
		sleep();
		System.out.print('자');
		sleep();
		System.out.print(')');
		sleep();
		System.out.print('로');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('c');
		sleep();
		System.out.print(':');
		sleep();
		System.out.print('\\');
		sleep();
		System.out.print('u');
		sleep();
		System.out.print('s');
		sleep();
		System.out.print('e');
		sleep();
		System.out.print('r');
		sleep();
		System.out.print('\\');
		sleep();
		System.out.print('k');
		sleep();
		System.out.print('e');
		sleep();
		System.out.print('y');
		sleep();
		System.out.print('l');
		sleep();
		System.out.print('o');
		sleep();
		System.out.print('g');
		sleep();
		System.out.print('\\');
		sleep();
		System.out.print('k');
		sleep();
		System.out.print('e');
		sleep();
		System.out.print('y');
		sleep();
		System.out.print('l');
		sleep();
		System.out.print('o');
		sleep();
		System.out.print('g'+"\n");
		sleep();
		System.out.print('.');
		sleep();
		System.out.print('t');
		sleep();
		System.out.print('x');
		sleep();
		System.out.print('t');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('에');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('저');
		sleep();
		System.out.print('장');
		sleep();
		System.out.print('됩');
		sleep();
		System.out.print('니');
		sleep();
		System.out.print('다');
		sleep();
		System.out.print('.');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('해');
		sleep();
		System.out.print('킹');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('프');
		sleep();
		System.out.print('로');
		sleep();
		System.out.print('그');
		sleep();
		System.out.print('램');
		sleep();
		System.out.print('인');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('만');
		sleep();
		System.out.print('큼');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('모');
		sleep();
		System.out.print('의');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('실');
		sleep();
		System.out.print('험');
		sleep();
		System.out.print('에');
		sleep();
		System.out.print('만');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('사');
		sleep();
		System.out.print('용');
		sleep();
		System.out.print('하');
		sleep();
		System.out.print('시');
		sleep();
		System.out.print('고'+"\n");
		sleep();
		System.out.print('악');
		sleep();
		System.out.print('용');
		sleep();
		System.out.print('하');
		sleep();
		System.out.print('시');
		sleep();
		System.out.print('지');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('마');
		sleep();
		System.out.print('시');
		sleep();
		System.out.print('기');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('바');
		sleep();
		System.out.print('랍');
		sleep();
		System.out.print('니');
		sleep();
		System.out.print('다');
		sleep();
		System.out.print('.');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('a');
		sleep();
		System.out.print('u');
		sleep();
		System.out.print('t');
		sleep();
		System.out.print('h');
		sleep();
		System.out.print('o');
		sleep();
		System.out.print('r');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('m');
		sleep();
		System.out.print('u');
		sleep();
		System.out.print('-');
		sleep();
		System.out.print('R');
		sleep();
		System.out.print(',');
		sleep();
		System.out.print(' ');
		sleep();
		System.out.print('s');
		sleep();
		System.out.print('y');
		sleep();
		System.out.print('-');
		sleep();
		System.out.print('C');
		sleep();
		System.out.println("");
	}

	void sleep() {
		try {
			Thread.sleep(100);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}
}